version: 2

jobs:

  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive apt install tzdata
      - run: apt-get install -y git python3-h5py python3-netcdf4 python3-pip
      - run: pip3 install -U pytest pytest-cov flake8 black
      - checkout
      # format and lint
      - run: LC_ALL=C.UTF-8 black --check setup.py meshio/ test/*.py
      - run: flake8 setup.py meshio/ test/*.py
      # The actual test
      - run: pip3 install .[all]
      - run: cd test/ && pytest --cov meshio
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
